name: BedWarsProxy
version: ${gitVer}${project.version}
description: Arena connecter for BedWars1058
main: com.andrei1058.bedwars.proxy.BedWarsProxy
authors: [andrei1058, MrKitty_Cat]
api-version: '1.13'
softdepend:
  - Parties
  - Partys
  - PartyAndFriends
  - PlaceholderAPI
  - Spigot-Party-API-PAF
